apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-jenkins-deployment-master
  namespace: kubernetes-cluster-arshdeepsingh
  labels:
    app: java-jenkins-demo-app-master
spec: 
  replicas: 4
  selector:
    matchLabels:
        app: java-jenkins-demo-app-master
  template:
    metadata:
        labels:
          app: java-jenkins-demo-app-master
    spec:
      containers:
        - name: java-jenkins-demo-app-master
          image: arshdeepsingh070/devops-home-assignment:master-latest
          ports:
            -  name: http
               containerPort: 8080
               protocol: TCP
---
apiVersion: v1
kind: Service
metadata: 
    name: java-jenkins-service-master
    namespace: kubernetes-cluster-arshdeepsingh
spec: 
   type: NodePort
   selector:
       app: java-jenkins-demo-app-master
   ports:
      - protocol: TCP
        nodePort: 30157
        port: 8080
        targetPort: 8080              
