apiVersion: apps/V1
kind:  deployment
metadata:
     name: java-demo-project
     labels:
         app: java-app
 spec: 
  replicas: 3
  selector:
      matchlabels:
        app: java-app
  template:
      metadata:
        labels:
          app: java-app
       spec:
         containers:
           - name: java-app
             image: arshdeepsingh070/devops-home-assignment:latest
             ports:
               -  name: http
                  containerPort: 80
                  protocol: TCP
---
apiVersion: v1
kind: Service
metadata: 
    name: java-app
spec: 
   type: NodePort
   selector:
       app: java-app
   ports:
      - protocol: TCP
        nodePort: 30105
        port: 80
        targetPort: 80

               
             
